-- 001_init.sql
BEGIN;
CREATE TABLE IF NOT EXISTS migrations (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  run_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- organisations
CREATE TABLE IF NOT EXISTS Organisations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- users
CREATE TABLE IF NOT EXISTS Users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  organisationId INTEGER,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- employees
CREATE TABLE IF NOT EXISTS Employees (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  organisationId INTEGER,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  email VARCHAR(255),
  phone VARCHAR(50),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- teams
CREATE TABLE IF NOT EXISTS Teams (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  organisationId INTEGER,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- join table employee_teams (EmployeeTeams)
CREATE TABLE IF NOT EXISTS EmployeeTeams (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  employeeId INTEGER,
  teamId INTEGER,
  assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- logs
CREATE TABLE IF NOT EXISTS Logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  organisationId INTEGER,
  userId INTEGER,
  action VARCHAR(255),
  meta TEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
